# Generated by Django 4.2.3 on 2023-07-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=3)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_kms', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_ride_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
