# Generated by Django 4.2.3 on 2023-07-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricingconfig_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_kms',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_ride_time',
        ),
    ]
